services:
  postgres:
    image: postgres:16-alpine
    container_name: sidago-postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi-backend:
    image: node:20-alpine
    container_name: sidago-strapi
    working_dir: /app
    command: sh -c "npm install && npm run develop"
    env_file:
      - strapi-backend/.env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    volumes:
      - ./strapi-backend:/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  sidago-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidago-frontend
    env_file:
      - .env
    ports:
      - "9005:9005"
    restart: always
    depends_on:
      - strapi-backend

volumes:
  postgres_data:
