import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../styles/default.css";
// import "../styles/light.css";
// import "../styles/responsive.css";
// import "../styles/style_1.css";
// import "../styles/jquery-ui.css";
// import "../styles/style.min_2.css";
// import "../styles/js_composer.css";
// import "../styles/case-study-style.css";
import { getGlobalSettings } from "../lib/api";
import { GlobalProvider } from "../hooks/useGlobal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};
// import localFont from "next/font/local";

// const blender = localFont({
//   src: [
//     {
//       path: "/fonts/blender_book-s.p.17e5766d.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "/fonts/blender_medium-s.p.f824e332.woff2",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   display: "swap",
// });


export default async function RootLayout({ children }) {
  const settings = await getGlobalSettings();
  console.log("🚀 ~ RootLayout ~ settings:", settings);

  if (!settings) {
    return <div>No data found</div>;
  }

  const version = settings.version?.label;
  const versionCSS =
    version === "v1"
      ? [
          "/styles/default.css",
          "/styles/light.css",
          "/styles/responsive.css",
          "/styles/style_1.css",
          "/styles/jquery-ui.css",
          "/styles/style.min_2.css",
          "/styles/js_composer.css",
          "/styles/case-study-style.css",
        ]
      : [];

  return (
    // <html lang="en" className={blender.className}>
    <html lang="en">
      <head>
        {/* Dynamic CSS based on version */}
        {versionCSS.map((href) => (
          <link key={href} rel="stylesheet" href={href} />
        ))}
      </head>
      <body
        className={`version-${version} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider settings={settings}>{children}</GlobalProvider>
      </body>
    </html>
  );
}
