import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/default.css";
import "../styles/light.css";
import "../styles/responsive.css";
import "../styles/style_1.css";
import "../styles/jquery-ui.css";
import "../styles/style.min_2.css";
import "../styles/js_composer.css";
import "../styles/case-study-style.css";
import { getGlobalSettings } from "../lib/api";
import { GlobalProvider } from "../hooks/useGlobal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const settings = await getGlobalSettings();

  if (!settings) {
    return <div>No data found</div>;
  }

  return (
    <html lang="en">
      <body>
        <GlobalProvider settings={settings}>{children}</GlobalProvider>
      </body>
    </html>
  );
}
