import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/default.css";
import "../styles/light.css";
import "../styles/responsive.css";
import "../styles/style_1.css";
import "../styles/jquery-ui.css";
import "../styles/style.min_2.css";
import "../styles/js_composer.css";
import "../styles/case-study-style.css";
import Topbar from "../components/sections/homepage/Topbar";
import Navbar from "../components/sections/homepage/Navbar";
import ClientsCarousel from "../components/sections/homepage/ClientsCarousel";
import Footer from "../components/sections/homepage/Footer";
import { fetchAPI } from "../lib/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await fetchAPI("global?populate=*");

  const settings = data.data;
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="home wp-singular page-template page-template-home-template page-template-home-template-php page page-id-11 page-parent custom-background wp-theme-exception wp-child-theme-exception-child wpb-js-composer js-comp-ver-4.12.1 vc_responsive">
          <div className="pageWrapper">
            <div id="headWrapper" className="head-style1 clearfix">
              <Topbar settings={settings} />
              <Navbar settings={settings} />
              <div id="contentWrapper">
                {children}
                <ClientsCarousel />
                <Footer />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
